export const SET_CARD_NUMBER: 'SET_CARD_NUMBER' = 'SET_CARD_NUMBER';
export const SET_EXPIRATION_DATE_MONTH: 'SET_EXPIRATION_DATE_MONTH' = 'SET_EXPIRATION_DATE_MONTH';
export const SET_EXPIRATION_DATE_YEAR: 'SET_EXPIRATION_DATE_YEAR' = 'SET_EXPIRATION_DATE_YEAR';
export const SET_CVV: 'SET_CVV' = 'SET_CVV';
export const START_PAYMENT_REQUEST: 'START_PAYMENT_REQUEST' = 'START_PAYMENT_REQUEST';
export const START_PAYMENT_SUCCESS: 'START_PAYMENT_SUCCESS' = 'START_PAYMENT_SUCCESS';
export const START_PAYMENT_FAILED: 'START_PAYMENT_FAILED' = 'START_PAYMENT_FAILED';