export const SET_CARD_NUMBER: 'SET_CARD_NUMBER' = 'SET_CARD_NUMBER';
export const SET_EXPIRATION_DATE: 'SET_EXPIRATION_DATE' = 'SET_EXPIRATION_DATE';
export const SET_CVV: 'SET_CVV' = 'SET_CVV';
export const START_PAYMENT_REQUEST: 'START_PAYMENT_REQUEST' = 'START_PAYMENT_REQUEST';
export const START_PAYMENT_SUCCESS: 'START_PAYMENT_SUCCESS' = 'START_PAYMENT_SUCCESS';
export const START_PAYMENT_FAILED: 'START_PAYMENT_FAILED' = 'START_PAYMENT_FAILED';